feat: spin render when deleting file
briefercloud/briefer pull request #88
Opened 2024-09-18 00:11 UTC by Samuel-Brito19

Adding spinner to indicate when the user delete a file.

Issue: #62

2024-09-18 00:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/briefercloud/briefer?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/briefercloud/briefer?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/briefercloud/briefer?pullRequest=88) it.</sub>

2024-09-19 19:31 UTC, vieiralucas commented
Hi @Samuel-Brito19 can you sign the CLA?

2024-09-19 21:16 UTC, Samuel-Brito19 commented
Done!

2024-09-23 14:37 UTC, vieiralucas requested changes
Hello @Samuel-Brito19 

Thank you so much for your PR, what you did here works but I would like to do it differently, can you check my comment and let me know if it makes sense?

Thank you.

2024-09-23 14:37 UTC, vieiralucas commented on apps/web/src/components/Files.tsx
> +    setIsDeleting(false)
I think we should use the existing `isDeleting` prop.
What we need to do here is debug why it is not becoming `true` when the data source is being removed.

We should check the parent of this component, check what it is giving as the `isDeleting` prop and why it is not passing `true` while the file is being deleted.

2024-09-23 19:37 UTC, vieiralucas commented on apps/web/src/components/Files.tsx
> +                          isDeleting={deleting[file.name]}
genius!

2024-09-23 19:39 UTC, merged